# Building the relationship stability outcome

We follow each respondent's **2017 partner** through the 2020 and 2022 follow-ups and record
whether that relationship ended.

## 1. Loading the cleaned data

Load the 2,862 partnered respondents saved by `01_clean`.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/hcmst2017_clean.csv", low_memory=False)
df.shape

(2862, 730)

## 2. Seeing who answered the follow-ups

HCMST is a panel: the same respondents were re-surveyed in 2020 and 2022, and no new respondents
were added. Some people did not answer one or both follow-ups (attrition). This table shows who
answered each follow-up.

In [2]:
pd.crosstab(df["w2_surveyed"], df["w3_surveyed"], margins=True)

w3_surveyed    no   yes   All
w2_surveyed
no           1049    97  1146
yes           416  1300  1716
All          1465  1397  2862

## 3. Tracking each 2017 relationship

For each respondent, we record what happened to their 2017 relationship at each follow-up:
Together, Broke up, Partner died, or Not surveyed.

- **2020** (`w2_relationship_end`): covers both married and unmarried couples. Separation and
  divorce count as breaking up.
- **2022** (`w3_relationship_end_combo`): a breakup or death only counts if it involves the
  **2017 partner** (`w3_breakup_source` = "2017 wave"). Breakups with partners met after 2017
  are ignored.

In [3]:
def status_2020(row):
    if row["w2_surveyed"] != "yes":
        return "Not surveyed"
    end = row["w2_relationship_end"]
    if end in ["Separation or other breakup", "Divorce"]:
        return "Broke up"
    if end == "Partner died":
        return "Partner died"
    return "Together"


def status_2022(row):
    if row["w3_surveyed"] != "yes":
        return "Not surveyed"
    end = row["w3_relationship_end_combo"]
    with_2017_partner = row["w3_breakup_source"] == "2017 wave"
    if end in ["Separated/ Broke up", "Got Divorced"] and with_2017_partner:
        return "Broke up"
    if end == "Partner died" and with_2017_partner:
        return "Partner died"
    return "Together"


df["status_2020"] = df.apply(status_2020, axis=1)
df["status_2022"] = df.apply(status_2022, axis=1)

pd.crosstab(df["status_2020"], df["status_2022"], margins=True)

/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3202458970.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["status_2020"] = df.apply(status_2020, axis=1)
/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3202458970.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["status_2022"] = df.apply(status_2022, axis=1)

status_2022   Broke up  Not surveyed  Partner died  Together   All
status_2020
Broke up             0            48             0       135   183
Not surveyed        15          1049             8        74  1146
Partner died         0            12             0        29    41
Together            20           356            17      1099  1492
All                 35          1465            25      1337  2862

## 4. Flagging breakups and setting aside partner deaths

For each couple we create:
- `broke_up` = 1 if the 2017 relationship ended in a breakup or divorce by 2022, 0 otherwise.
- `partner_died` = the 2017 partner died during follow-up. These are not counted as breakups,
  since they do not reflect a decision to separate.
- `followed_up` = the respondent answered at least one follow-up (2020 or 2022).

The couple-level analysis sample (`in_sample`) keeps respondents who were followed up and whose
partner did not die. Partner deaths are handled separately in the panel set-up (Section 5).

In [4]:
# Partner died at either follow-up (and not after an earlier breakup)
df["partner_died"] = (df["status_2020"] == "Partner died") | (
    (df["status_2020"] != "Broke up") & (df["status_2022"] == "Partner died")
)

# Broke up with the 2017 partner by 2020 or by 2022 (1 = yes, 0 = no)
df["broke_up"] = (
    (df["status_2020"] == "Broke up")
    | ((df["status_2020"] != "Partner died") & (df["status_2022"] == "Broke up"))
).astype(int)

# Answered at least one follow-up
df["followed_up"] = (df["w2_surveyed"] == "yes") | (df["w3_surveyed"] == "yes")

# Couple-level analysis sample: followed up, partner did not die
df["in_sample"] = df["followed_up"] & ~df["partner_died"]

print("Partner deaths:", df["partner_died"].sum())
print("Followed up:", df["followed_up"].sum())
print("In sample:", df["in_sample"].sum())

# Check that married AND unmarried couples are both included
sample = df[df["in_sample"]]
pd.crosstab(sample["w1_partnership_status"], sample["broke_up"], margins=True)

Partner deaths: 66
Followed up: 1813
In sample: 1747

/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3463582811.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["partner_died"] = (df["status_2020"] == "Partner died") | (
/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3463582811.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["broke_up"] = (
/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3463582811.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["followed_up"] = (df["w2_surveyed"] == "yes") | (df["w3_surveyed"] == "yes")
/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3463582811.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["in_sample"] = df["followed_up"] & ~df["partner_died"]

broke_up                   0    1   All
w1_partnership_status
married                 1268   66  1334
partnered, not married   261  152   413
All                     1529  218  1747

## 5. Setting up one row per survey gap

To account for the panel structure, each couple contributes one row per follow-up gap during
which we observed them: 2017–2020, then 2020–2022 if still together and surveyed again.
Respondents who skipped 2020 but answered in 2022 contribute one 2017–2022 row.

A couple stops contributing rows after a breakup, after dropping out of the survey, or after the
partner's death. Couples whose partner died between 2020 and 2022 still contribute their
2017–2020 row, since we know they stayed together over that period (censoring).

In [5]:
rows = []

for _, person in df[df["followed_up"]].iterrows():
    s2020 = person["status_2020"]
    s2022 = person["status_2022"]
    pid = person["caseid_new"]

    # Skipped 2020, answered 2022: one long 2017-2022 gap
    if s2020 == "Not surveyed":
        if s2022 in ["Together", "Broke up"]:
            rows.append({"caseid_new": pid, "period": "2017-2022", "broke_up": int(s2022 == "Broke up")})
        continue

    # Partner died before 2020: no completed gap, so no rows
    if s2020 == "Partner died":
        continue

    # 2017-2020 gap
    rows.append({"caseid_new": pid, "period": "2017-2020", "broke_up": int(s2020 == "Broke up")})

    # 2020-2022 gap: only if still together in 2020 and answered in 2022
    if s2020 == "Together" and s2022 in ["Together", "Broke up"]:
        rows.append({"caseid_new": pid, "period": "2020-2022", "broke_up": int(s2022 == "Broke up")})

pp = pd.DataFrame(rows)

print("Rows:", len(pp), "| Couples:", pp["caseid_new"].nunique(), "| Breakups:", pp["broke_up"].sum())
pd.crosstab(pp["period"], pp["broke_up"], margins=True)

Rows: 2883 | Couples: 1764 | Breakups: 218

broke_up      0    1   All
period
2017-2020  1492  183  1675
2017-2022    74   15    89
2020-2022  1099   20  1119
All        2665  218  2883

## 6. Saving the outcome data

We save two files to `data/processed/`, each linked to the cleaned data by `caseid_new`:

- `hcmst2017_outcome.csv`: one row per respondent, with their 2020 and 2022 status, whether they
  broke up, whether their partner died, whether they were followed up, and whether they are in the
  analysis sample.
- `hcmst2017_person_period.csv`: one row per couple per survey gap, used for the panel models.

In [6]:
# One row per respondent: just the ID and the new outcome columns
outcome_cols = ["caseid_new", "status_2020", "status_2022", "broke_up",
                "partner_died", "followed_up", "in_sample"]
df[outcome_cols].to_csv("../data/processed/hcmst2017_outcome.csv", index=False)

# One row per couple per survey gap
pp.to_csv("../data/processed/hcmst2017_person_period.csv", index=False)

print("Outcome file:", df[outcome_cols].shape)
print("Person-period file:", pp.shape)

Outcome file: (2862, 7)
Person-period file: (2883, 3)

## 7. Checking who dropped out (attrition)

We compare the share of respondents who answered at least one follow-up (2020 or 2022) across
income, race and marital status in 2017. If follow-up rates differ between groups, our sample of
followed-up couples may not represent all 2017 couples equally.

In [7]:
# Simple race grouping for this check (the full race coding is done in 03_race)
race_map = {"White, Non-Hispanic": "White", "Black, Non-Hispanic": "Black", "Hispanic": "Hispanic"}
df["race_group"] = df["w1_ppethm"].map(race_map).fillna("Other")

# Follow-up rate for each group of each characteristic
checks = [("income_tertile", "Income", ["Low", "Middle", "High"]),
          ("race_group", "Race", ["White", "Black", "Hispanic", "Other"]),
          ("w1_partnership_status", "Marital status", ["married", "partnered, not married"])]

tables = []
for var, label, order in checks:
    t = df.groupby(var)["followed_up"].agg(n="size", pct_followed_up="mean").reindex(order)
    t["pct_followed_up"] = (t["pct_followed_up"] * 100).round(1)
    t.insert(0, "characteristic", label)
    t.index.name = "group"
    tables.append(t.reset_index())

attrition = pd.concat(tables, ignore_index=True)
attrition.to_csv("../output/tables/attrition_by_group.csv", index=False)
attrition

/var/folders/tk/j75m2rk91ll9tl_rymw764qh0000gn/T/ipykernel_22611/3628210542.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["race_group"] = df["w1_ppethm"].map(race_map).fillna("Other")

                    group  characteristic     n  pct_followed_up
0                     Low          Income  1095             56.3
1                  Middle          Income  1058             67.8
2                    High          Income   709             67.7
3                   White            Race  2082             65.6
4                   Black            Race   229             55.0
5                Hispanic            Race   347             55.6
6                   Other            Race   204             62.7
7                 married  Marital status  2085             66.3
8  partnered, not married  Marital status   777             55.5

## 8. Saving summary tables

Save the key descriptive tables to `output/tables/` so every number in the slides and paper can be
traced to this notebook: who answered the follow-ups, breakups by survey gap, and breakups for
married and unmarried couples.

In [8]:
# Who answered the follow-ups
followup = pd.crosstab(df["w2_surveyed"], df["w3_surveyed"], margins=True)
followup.to_csv("../output/tables/followup_by_wave.csv")

# Breakups by survey gap (time order)
by_gap = pp.groupby("period")["broke_up"].agg(couples="size", breakups="sum")
by_gap = by_gap.reindex(["2017-2020", "2020-2022", "2017-2022"])
by_gap["breakup_rate_pct"] = (by_gap["breakups"] / by_gap["couples"] * 100).round(1)
by_gap.to_csv("../output/tables/breakups_by_gap.csv")

# Breakups for married vs unmarried couples (analysis sample)
sample = df[df["in_sample"]]
by_marital = sample.groupby("w1_partnership_status")["broke_up"].agg(couples="size", breakups="sum")
by_marital["breakup_rate_pct"] = (by_marital["breakups"] / by_marital["couples"] * 100).round(1)
by_marital.to_csv("../output/tables/breakups_by_marital_status.csv")

print(by_gap)
print()
print(by_marital)

           couples  breakups  breakup_rate_pct
period
2017-2020     1675       183              10.9
2020-2022     1119        20               1.8
2017-2022       89        15              16.9

                        couples  breakups  breakup_rate_pct
w1_partnership_status
married                    1334        66               4.9
partnered, not married      413       152              36.8

# 9. final check

In [9]:
assert len(df) == 2862, "Should be 2,862 partnered respondents"
assert df["partner_died"].sum() == 66, "Should be 66 partner deaths"
assert (df["partner_died"] & (df["broke_up"] == 1)).sum() == 0, "Partner deaths must not count as breakups"
assert df["in_sample"].sum() == 1747, "Should be 1,747 couples in the analysis sample"
assert df.loc[df["in_sample"], "broke_up"].sum() == 218, "Should be 218 breakups"
assert set(sample["w1_partnership_status"]) == {"married", "partnered, not married"}, "Married AND unmarried couples must be included"
assert len(pp) == 2883 and pp["broke_up"].sum() == 218, "Person-period data should have 2,883 rows and 218 breakups"

print("All checks passed ✓")

All checks passed ✓