In [1]:
import pandas as pd

df = pd.read_csv('../data/processed/hcmst_analysis_base.csv')
print(df.shape)
df.head()

(4002, 25)

,caseid_new,weight1,weight2,weight3,ppincimp,ppeduc,q10,q23,income_ordinal,income_tertile,...,w2_q5,w2_q9,w3_q5,w3_q9,how_long_relationship,ppethm,pp2_ppethm,pp3_ppethm,q6a,q6b
0,22526,4265,4265.0,4265.0,"$20,000 to $24,999",bachelors degree,associate degree,partner earned more,7,Low,...,yes,NaN,yes,NaN,7.0,hispanic,hispanic,Hispanic,no (not latino or hispanic),white
1,23286,16485,16485.0,16485.0,"$40,000 to $49,999",masters degree,bachelor's degree,i earned more,11,Middle,...,NaN,NaN,NaN,NaN,8.0,"white, non-hispanic","white, non-hispanic","White, Non-Hispanic",no (not latino or hispanic),white
2,25495,52464,NaN,NaN,"$35,000 to $39,999",high school graduate - high school diploma or ...,NaN,NaN,10,Low,...,NaN,NaN,NaN,NaN,NaN,"black, non-hispanic","black, non-hispanic","Black, Non-Hispanic",NaN,NaN
3,26315,4575,4575.0,4575.0,"$40,000 to $49,999",associate degree,hs graduate or ged,i earned more,11,Middle,...,no,we broke up,NaN,NaN,8.0,"white, non-hispanic","white, non-hispanic","White, Non-Hispanic",no (not latino or hispanic),white
4,27355,12147,NaN,NaN,"$40,000 to $49,999",high school graduate - high school diploma or ...,NaN,NaN,11,Middle,...,NaN,NaN,NaN,NaN,NaN,"white, non-hispanic","white, non-hispanic","White, Non-Hispanic",NaN,NaN

In [2]:
[col for col in df.columns if 'ethm' in col.lower() or 'q6b' in col.lower()]

['ppethm', 'pp2_ppethm', 'pp3_ppethm', 'q6b']

In [3]:
df['ppethm'].value_counts(dropna=False)

ppethm
white, non-hispanic       3007
hispanic                   387
black, non-hispanic        321
2+ races, non-hispanic     165
other, non-hispanic        122
Name: count, dtype: int64

In [4]:
df['pp2_ppethm'].value_counts(dropna=False)

pp2_ppethm
white, non-hispanic       2828
hispanic                   351
NaN                        309
black, non-hispanic        286
other, non-hispanic        116
2+ races, non-hispanic     112
Name: count, dtype: int64

In [5]:
df['pp3_ppethm'].value_counts(dropna=False)

pp3_ppethm
White, Non-Hispanic       2007
NaN                       1358
Hispanic                   279
Black, Non-Hispanic        195
Other, Non-Hispanic         83
2+ Races, Non-Hispanic      80
Name: count, dtype: int64

In [6]:
df['q6b'].value_counts(dropna=False)

q6b
white                                2528
NaN                                   990
black or african american             253
other (please specify)                120
asian or pacific islander              65
american indian, aleut, or eskimo      25
refused                                21
Name: count, dtype: int64

In [7]:
df['ppethm'] = df['ppethm'].str.lower()
df['pp2_ppethm'] = df['pp2_ppethm'].str.lower()
df['pp3_ppethm'] = df['pp3_ppethm'].str.lower()

In [8]:
df['respondent_race_raw'] = df['ppethm'].fillna(df['pp2_ppethm']).fillna(df['pp3_ppethm'])
df['respondent_race_raw'].value_counts(dropna=False)

respondent_race_raw
white, non-hispanic       3007
hispanic                   387
black, non-hispanic        321
2+ races, non-hispanic     165
other, non-hispanic        122
Name: count, dtype: int64

In [9]:
race_map = {
    'white, non-hispanic': 'White',
    'hispanic': 'Hispanic',
    'black, non-hispanic': 'Black',
    '2+ races, non-hispanic': 'Other/Multiracial',
    'other, non-hispanic': 'Other/Multiracial'
}
df['respondent_race_group'] = df['respondent_race_raw'].map(race_map)
df['respondent_race_group'].value_counts(dropna=False)

respondent_race_group
White                3007
Hispanic              387
Black                 321
Other/Multiracial     287
Name: count, dtype: int64

In [10]:
partner_race_map = {
    'white': 'White',
    'black or african american': 'Black',
    'asian or pacific islander': 'Other/Multiracial',
    'american indian, aleut, or eskimo': 'Other/Multiracial',
    'other (please specify)': 'Other/Multiracial',
    'refused': None
}
df['partner_race_group'] = df['q6b'].map(partner_race_map)
df['partner_race_group'].value_counts(dropna=False)

partner_race_group
White                2528
NaN                  1011
Black                 253
Other/Multiracial     210
Name: count, dtype: int64

In [11]:
df['respondent_race_group'].value_counts(dropna=False)

respondent_race_group
White                3007
Hispanic              387
Black                 321
Other/Multiracial     287
Name: count, dtype: int64

In [12]:
race_table = df['respondent_race_group'].value_counts(dropna=False).reset_index()
race_table.columns = ['Race Group', 'Count']
race_table.to_csv('../output/tables/race_distribution.csv', index=False)
race_table

          Race Group  Count
0              White   3007
1           Hispanic    387
2              Black    321
3  Other/Multiracial    287